cms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('content.urls')),
    path('admin/', admin.site.urls),
    path('oauth/', include('social_django.urls', namespace='social')), #Je to potreba
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path
from .views import articles, article, category
from . import views
from django.urls import include

app_name = 'content'

urlpatterns = [
    path('', articles, name='articles'),
    path('article/<int:id>/', article, name='article'),
    path('rubrika/<int:id>/', category, name='category'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('comment/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('reload/', views.reload_images, name='reload_images'),
]

content/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

class Biom(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = "Biomes"

    def __str__(self):
        return self.name

#https://www.youtube.com/watch?v=GNsuF4xB80E&ab_channel=DaveGray

class Article(models.Model):
    title = models.CharField(max_length=200)
    zakladniInfo = models.TextField(default="Neznámé")
    dodatkovyText = models.TextField(default="Neznámé")
    vyroba = models.TextField(max_length=200, default="Neznámé")
    image = models.ImageField(default='default.jpg', blank=True)
    version = models.TextField(max_length=50, default="Neznámé")
    lastUpdate = models.DateTimeField()
    biom = models.ForeignKey(Biom, on_delete=models.SET_NULL, null=True)
    categories = models.ManyToManyField(Category, related_name='articles')
    vote_sum = models.IntegerField(default=0)
    vote_count = models.IntegerField(default=0)
 
    def vote_avg(self):
        return self.vote_sum / self.vote_count if self.vote_count > 0 else 0      

    def __str__(self):
        return self.title


class Comment(models.Model):
    name = models.CharField(max_length=100)
    text = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    time = models.DateTimeField(auto_now_add=True, null=True)
    ip = models.GenericIPAddressField(default=None, null=True)
    user_agent = models.CharField(max_length=200, default=None, null=True)

    def __str__(self):
        return f"{self.name} ({self.user.username if self.user else 'nepřiřazen'})"

content/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Field

class CommentForm(forms.Form):
    name = forms.CharField(label='Nick', max_length=100)
    text = forms.CharField(label='Co na to říkáte?', widget=forms.Textarea)

class LoginForm(forms.Form):
    username = forms.CharField(label='Uživatelské jméno', max_length=100)
    password = forms.CharField(label='Heslo', widget=forms.PasswordInput)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Row(
                Field('username'),
                Field('password'),
            ),
            Submit('submit', 'Přihlásit se', css_class='btn-primary')
        )  

class LogoutForm(forms.Form):
    confirm = forms.BooleanField(label="Opravdu se chcete odhlásit?")


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=150, required=True)
    email = forms.EmailField(required=True)
    password1 = forms.CharField(widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(widget=forms.PasswordInput, required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Row(
                Field('email'),
                Field('username'),
                Field('password1'),
                Field('password2'),
            ),            
            Submit('submit', 'Vytvořit účet', css_class='btn-primary')
        )

content/views.py
from django.shortcuts import render
from django.http import HttpResponse as HTTPResponse
from django.http import HttpResponseRedirect as HTTPResponseRedirect
from django.urls import reverse
import json
from .models import Article, Category, Comment
from .forms import CommentForm
from django.contrib.auth import authenticate, login, logout 
from .forms import LoginForm, LogoutForm
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.models import User
from .forms import RegisterForm
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404, redirect
from .models import Comment  # nebo Review, podle pojmenování
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
import os
import shutil
from django.conf import settings
from django.shortcuts import render, redirect



# Create your views here.
def articles(request):
    articles = Article.objects.all()
    categories = Category.objects.all()  # Získání všech kategorií

    context = {
        'articles': articles,
        'categories': categories,  # Přidání kategorií do kontextu
    }

    form = CommentForm()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            comment = Comment()
            comment.name = data['name']
            comment.text = data['text']
            comment.article = article
            comment.ip = request.META.get('REMOTE_ADDR')
            comment.user_agent = request.META.get('HTTP_USER_AGENT')
            comment.save()
            return HTTPResponseRedirect(reverse('content:article', args=[id]))
        
    if request.method == 'GET' and 'vote' in request.GET:
        cookiename=f'voted_{article.id}'
        if cookiename in request.COOKIES:
            return HTTPResponseRedirect(reverse('content:article', args=[id]))
        
        vote = int(request.GET['vote'])
        if vote <= 5 and vote >= 1:
            article.vote_sum += vote
            article.vote_count += 1
            article.save()

            response = HTTPResponseRedirect(reverse('content:article', args=[id]))
            response.set_cookie(cookiename, '1')
            return response
        
    return render(request, 'content/articles.html', context)

def article(request, id):
    article = Article.objects.get(id=id)

    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            comment = Comment()
            comment.name = data['name']
            comment.text = data['text']
            comment.user = request.user if request.user.is_authenticated else None
            comment.article = article
            comment.ip = request.META.get('REMOTE_ADDR') 
            comment.user_agent = request.META.get('HTTP_USER_AGENT')
            comment.save()

            return HTTPResponseRedirect(reverse('content:article', args=[id]))


    if request.method == 'GET' and 'vote' in request.GET:
        cookiename=f'voted_{article.id}'
        if cookiename in request.COOKIES:
            return HTTPResponseRedirect(reverse('content:article', args=[id]))
        
        vote = int(request.GET['vote'])
        if vote <= 9 and vote >= 1:
            article.vote_sum += vote
            article.vote_count += 1
            article.save()

            response = HTTPResponseRedirect(reverse('content:article', args=[id]))
            
            response.set_cookie(cookiename, '1')
            return response
    
    return render(request, 'content/article.html', {'article': article, 'form': form})

def category(request, id):
    category = Category.objects.get(id=id)

    articles = category.articles.all()
    
    return render(request, 'content/category.html', {'category':category, 'articles': articles})

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('content:login'))
            else:
                messages.warning(request, 'Neplatné přihlašovací údaje.')
    else:
        form = LoginForm()

    return render(request, 'content/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('content:login')
    else:
        # Můžeš zobrazit formulář pro potvrzení odhlášení
        form = LogoutForm()
        return render(request, 'content/logout.html', {'form': form})

def register_view(request):
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'content/register.html', {'register_form': form})

    elif request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']

            if password1 != password2:
                form.add_error('password2', 'Hesla se neshodují')
                return render(request, 'content/register.html', {'register_form': form})

            user = User.objects.create_user(username=username, email=email, password=password1)
            user.save()

            return redirect(reverse('content:login'))
        else:
            return render(request, 'content/register.html', {'register_form': form})

@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    # Uživatel může smazat, pokud je autor nebo má oprávnění
    if request.user == comment.user or request.user.has_perm('content.delete_comment'):
        comment.delete()
        return redirect(request.META.get('HTTP_REFERER', 'content:articles'))
    else:
        return HttpResponseForbidden("Nemáš oprávnění k odstranění tohoto komentáře.")
    
def reload_images(request):
    copied_files = []

    if request.method == 'POST':
        media_root = settings.MEDIA_ROOT
        static_root = settings.STATICFILES_DIRS[0]  # bez podsložky 'media'

        for root, dirs, files in os.walk(media_root):
            for file in files:
                src_path = os.path.join(root, file)
                rel_path = os.path.relpath(src_path, media_root)
                dest_path = os.path.join(static_root, rel_path)

                if not os.path.exists(dest_path):
                    os.makedirs(os.path.dirname(dest_path), exist_ok=True)
                    shutil.copy2(src_path, dest_path)
                    copied_files.append(rel_path)

        return render(request, 'content/reload.html', {
            'copied_files': copied_files,
            'done': True
        })

    return render(request, 'content/reload.html')

content/templates/content/article.html
{% extends 'content/base.html' %}
{% load static %}

{% block title %}
    <style>
        div .entita img {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 40%  !important;
        }
        table, th, td {
            padding: 10px;
            border: 1px solid black;
            background-color: rgb(206, 206, 206);
        }
        form div {
            margin-bottom: 15px;
        }

        textarea {
            width: 100%;
            height: 100px;
        }
    </style>
    {{ article.title }}
{% endblock %}

{% block main %}
    <table>
        <tr>
            <p>Nova verze</p>

            <td style="width:80%">
                <strong>Zákldní parametry:</strong>
            <p>{{ article.zakladniInfo|linebreaks }}</p>

            <strong>Kategorie:</strong>
            <p>
                {% for category in article.categories.all %}
                    <a href="{%url 'content:category' category.id %}">{{ category.name }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>

            <strong>Další informace:</strong>
            <p>{{ article.dodatkovyText|linebreaks|linebreaks}}</p>

            <strong>Jak k tomu přijít:</strong>
            <p>{{ article.vyroba|linebreaks}}</p>

            <strong>V jakém biomu jsem:</strong>
            <p>{{ article.biom }}</p>

            <strong>Od jaké verze je to tady s námi:</strong>
            <p>{{ article.version|linebreaks}}</p>

            </td>
            <td>
                <div class="entita">
                    <img src="{{ article.image.url }}" alt="{{ article.title }}">
                </div>
                <p>Jméno: {{ article.title }}</p>
            </td>
        </tr>
    </table>
    <div>
        hlasu {{ article.vote_count }}
        prumer {{ article.vote_avg }}
    </div>
    <div class="my-4">
        <h2>Váš názor mě zajímá...</h2>
        <ul class="list-group">
            <li class="list-group-item">
                <!-- <div class="center"><img class="logo" src="{% static 'Lite terraria wiki.png' %}" alt="Logo"></div> -->
                <a href="?vote=1" class="btn btn-primary">Děs, běs a hrůza<img src="{% static 'Heart0.png' %}" alt="mrtveSrdicko" style="width:42px;height:42px;"></a>
                <a href="?vote=2" class="btn btn-primary">Blivajs<img src="{% static 'Heart1.png' %}" alt="1cvtCervenoho" style="width:42px;height:42px;"></a>
                <a href="?vote=3" class="btn btn-primary">Mech<img src="{% static 'Heart2.png' %}" alt="2cvtCervenoho" style="width:42px;height:42px;"></a>
                <a href="?vote=4" class="btn btn-primary">Fádní<img src="{% static 'Heart3.png' %}" alt="3cvtCervenoho" style="width:42px;height:42px;"></a>
                <a href="?vote=5" class="btn btn-primary">Snaha byla<img src="{% static 'Heart.png' %}" alt="CerveneSrdce" style="width:42px;height:42px;"></a>
                <a href="?vote=6" class="btn btn-primary">Dobré<img src="{% static 'GoldenHeart1.png' %}" alt="1cvtZlateho" style="width:42px;height:42px;"></a>
                <a href="?vote=7" class="btn btn-primary">Užasné<img src="{% static 'GoldenHeart2.png' %}" alt="2cvtZlateho" style="width:42px;height:42px;"></a>
                <a href="?vote=8" class="btn btn-primary">Epické<img src="{% static 'GoldenHeart3.png' %}" alt="3cvtZlateho" style="width:42px;height:42px;"></a>
                <a href="?vote=9" class="btn btn-primary"><b>Legendární</b><img src="{% static 'GoldenHeart.png' %}" alt="ZlateSrdce" style="width:42px;height:42px;"></a>
            </li>
        </ul>
    </div>
    <div>
        <form action="" method="POST" class="mt-3">
            {% csrf_token %}
            
            <div class="mb-3">
                <label for="id_name" class="form-label">Nick:</label>
                {{ form.name }}
            </div>
        
            <div class="mb-3">
                <label for="id_text" class="form-label">Co na to říkáte?</label>
                {{ form.text }}
            </div>
        
            <button type="submit" class="btn btn-primary">Odeslat</button>
        </form>
    </div>
    <div>
        <div class="my-4">
            <h2>Komentáře</h2>
            <ul class="list-group">
                {% for comment in article.comments.all %}
                    <li class="list-group-item">
                        <div class="d-flex justify-content-between">
                            <p class="text-muted small">
                                Realné jméno: {{ comment.user.username|default:"Nepřihlášený uživatel" }}<br>
                                <!-- Jméno (z formuláře): {{ comment.name }} -->
                            </p>

                            <h5 class="mb-1">{{ comment.name }}</h5>
                            
                        </div>
                        <p class="mb-1">{{ comment.text }}</p>
                    </li>
                    {% if user == comment.user or perms.content.delete_review %}
                        <form method="POST" action="{% url 'content:delete_comment' comment.id %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm mt-2">Smazat</button>
                        </form>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>    </div>
    
    <a href="{% url 'content:articles' %}">Zpet na seznam</a>
{% endblock %}

content/templates/content/articles.html
{% extends 'content/base.html' %}
{% load static %}

{% block title %}
<style>
    div .entita img {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 100%  !important;
    }
    table, th, td {
        border-collapse: collapse;
        background-color: rgb(206, 206, 206);
    }
</style>
    Hlavni stranka - Lite terraria wiki
    <h2>O nás:</h2>
        <p>Lite terraria wiki je stránka, která vám poskytne informace o všech objektech v terrarii. Na této stránce najdete informace o všech objektech, které můžete najít v terrarii. </p>
    <hr>
{% endblock %}

{% block main %}
    <section>
        <div class="container">
    {% for article in articles %}
            <div class="item">
                <div class="box">
                    <h2><a href="{% url 'content:article' article.id %}">{{ article.title }}</a></h2>
                    <div class="entita">
                        <!-- <img src="{{ MEDIA_URL }}{{ article.image }}" alt="{{ article.title }}"> -->
                        <img src="{% static article.image %}" alt="{{ article.title }}">
                    </div>
                    <table style="width:100%">
                        <tr>
                            <td style="width:80%">
                            <p>Hodnocení: {{ article.vote_avg }} na {{ article.vote_count }} hlasů</a></p>
                            <p>Hodnocení v obrázku:</p>
                            {% if article.vote_count == 0 %}
                                <img src="{% static 'Question.png' %}" alt="?">
                            {% else %}
                                {% with article.vote_avg|floatformat:0 as rounded_vote %} 

                                {% if rounded_vote == "1" %}
                                    <img src="{% static 'Heart0.png' %}" alt="mrtveSrdicko" style="width:42px;height:42px;">
                                {% elif rounded_vote == "2" %}
                                    <img src="{% static 'Heart1.png' %}" alt="1cvtCervenoho" style="width:42px;height:42px;">
                                {% elif rounded_vote == "3" %}
                                    <img src="{% static 'Heart2.png' %}" alt="2cvtCervenoho" style="width:42px;height:42px;">
                                {% elif rounded_vote == "4" %}
                                    <img src="{% static 'Heart3.png' %}" alt="3cvtCervenoho" style="width:42px;height:42px;">
                                {% elif rounded_vote == "5" %}
                                    <img src="{% static 'Heart.png' %}" alt="cerveneSrdce" style="width:42px;height:42px;">
                                {% elif rounded_vote == "6" %}
                                    <img src="{% static 'GoldenHeart1.png' %}" alt="1cvtZlateho" style="width:42px;height:42px;">
                                {% elif rounded_vote == "7" %}
                                    <img src="{% static 'GoldenHeart2.png' %}" alt="2cvtZlateho" style="width:42px;height:42px;">
                                {% elif rounded_vote == "8" %}
                                    <img src="{% static 'GoldenHeart3.png' %}" alt="3cvtZlateho" style="width:42px;height:42px;">
                                {% elif rounded_vote == "9" %}
                                    <img src="{% static 'GoldenHeart.png' %}" alt="zlateSrdce" style="width:42px;height:42px;">
                                {% else %}
                                    <img src="{% static 'Question.png' %}" alt="?" style="width:42px;height:42px;">
                                {% endif %}

                                {% endwith %}
                            {% endif %}
                                <p>
                                    Kategorie:
                                    {% for category in article.categories.all %}
                                        {{ category.name }}{% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                </p>
                                <p>
                                    Info: {{ article.zakladniInfo|linebreaks }}
                                </p>
                            </td>
                            <td>
                                
                            </td>
                        </tr>
                        <tr>
                        </tr>
                    </table>
                </div>
            </div>
    {% endfor %}
        </div>
    </section>	
    <hr>

    <h2>Kategorie:</h2>
        <div class="greenBack">
            <p>Zde jsou všechny kategorie obsažené v Lite terraria wikipedii.</p>
            <p>Počet kategorií: {{ categories|length }}</p>
            <p>
            {% for category in categories %}
                <a href="{% url 'content:category' category.id %}">{{ category.name }}</a>{% if not forloop.last %}, {% endif %}
            {% endfor %}
            </p>
        </div>
{% endblock %}
        

content/templates/content/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Lite terraria wiki</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="icon" type="image/png" href="{% static 'Icon.png' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<style>
    .uvod img {
        width: 65%;
        height: 100px;
        height: auto;
    }
    .klicz-2 {
        width: 100%;
        height: 50px;
    }
</style>
<header>
    <div class="content"></div>

    <p id="Be"></p>

    <div class="progress-container">
        <div class="progress-bar" id="progress-bar"></div>
    </div>

    <!-- Hlavička  -->
    <div class="FP">
        <div class="wrapper">
            <div class="flexbox">
                <!--<div class="FBtn"><button id="theme" style="vertical-align:middle"><span>Tmavý/Světlý mód</span></button></div>-->
                <div class="Fbox one">
                    <!--<a href="#Be"><input type="button" id="button" value="Zpět na začátek"></a></div>-->
                    <a class="likeBtn" href="{% url 'content:articles' %}">Zpět na rozcestník</a></div>
                    
                <div class="Fbox two">
                    <div class="center">
                        Lite terraria wiki
                    </div>
                </div>

                {% if user.is_authenticated %}
                <div class="Fbox two">
                    Prihlasen jako: 
                        {{ user.username }}
                </div>
                {% endif %}
                
                <div class="Fbox three">
                    {% if user.is_authenticated %}

                    <a class="likeBtn" href="{% url 'content:logout' %}">Logout</a></div>

                    {% else %}
                    
                    <a class="likeBtn" href="{% url 'content:login' %}">Login</a></div>
                    
                    {% endif %}
                </div>
            </div>

        </div>
        <script>
            /*
            document.getElementById("theme").addEventListener("click", function () {
            if (window.matchMedia("(prefers-color-scheme: dark)").matches) document.body.classList.toggle("light-mode");
            else document.body.classList.toggle("dark-mode");
            });
            */
    
    
            window.onscroll = function() {
                updateProgressBar();
            };
    
            function updateProgressBar() {
                var scrollTop = document.documentElement.scrollTop;
                var scrollHeight = document.documentElement.scrollHeight - document.documentElement.clientHeight;
                var scrollPercent = (scrollTop / scrollHeight) * 100;
                document.getElementById("progress-bar").style.width = scrollPercent + "%";
            }
        </script>
    </div>

        <!-- Titulek  -->
        &nbsp;
        <div class="uvod">
            <div class="center"><img class="logo" src="{% static 'Lite terraria wiki.png' %}" alt="Logo"></div>
        </div>
        &nbsp;
        <hr>
</header>
<body>
    <div class="wrapper">
    <h1>{% block title %}{% endblock %}</h1>
    <main>
        {% block main %}
        {% endblock %}
    </main>

    <h1>Známost stránky</h1>

    <p>Počet kliknutí</p>
    <div id="klikz-2"></div>
    <script src="https://klikz.svs.gyarab.cz/hit/2?size=small&front=008000&back=ffffff"></script>
    
    <p>Tak ať jich je hodně</p>

    {% include 'content/footer.html' %}
    </div>
</body>
</html>

content/templates/content/footer.html
<footer>
    Tohle je zapati stranky
</footer>

content/templates/content/login.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f9;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .login-container {
            background: #fff;
            padding: 20px;
            border-radius: 25px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            width: 320px;
            padding: 45px;
        }
        .login-container h1 {
            text-align: center;
            margin-bottom: 20px;
            font-size: 24px;
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }
        .form-group input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        .form-group input:focus {
            border-color: #007bff;
            outline: none;
        }
        .login-btn {
            width: 100%;
            padding: 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 4px;
            font-size: 16px;
            cursor: pointer;
        }
        .login-btn:hover {
            background-color: #0056b3;
        }
        .register-link {
            text-align: center;
            margin-top: 10px;
        }
        .register-link a {
            color: #007bff;
            text-decoration: none;
        }
        .register-link a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="login-container">
        <h1>Login</h1>
        <form action="/login" method="POST">
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit" class="login-btn">Login</button>
        </form>
        <div class="register-link">
            <p>Don't have an account? <a href="/register">Register here</a></p>
        </div>
    </div>
</body>
</html> -->

{% extends "content/base.html" %}
{% load static %}
 
{% block title %}
 
<h1>Login</h1>
 
{% endblock %}
 
{% block main %}
 
<div class="homepage">
 
<form action="/login/" method="POST">

    {% csrf_token %}

    <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
    </div>

    <br>
 
    <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required> 
    </div>
    
    <br>

    <div style=" margin-left: 45px; font-size: 18px;">
        <button type="submit">Login</button>
    </div>

    <br>

</form>

<a href="{% url 'social:begin' 'google-oauth2' %}">Přihlásit se pomocí Google</a>

<p>Namáte-li účet, tak se zaregistujte zde -> <a href="{% url 'content:register' %}">Registrace</a></p>

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </li>
        {% endfor %}
    </ul>
{% endif %}

{% if user.is_authenticated %}

    <div class="alert alert-success" role="alert">
        Jste přihlášen jako {{ user.username }}.
    </div>

{% endif %}


</div>
 
{% endblock %}

content/templates/content/logout.html
{% extends "content/base.html" %}
 
{% block title %}
 
<h1>Logout</h1>
 
{% endblock %}
 
{% block main %}
 
<div class="homepage">
    
    {% if request.user.is_authenticated %}
    <p>Jste přihlášen jako {{ request.user.username }}</p>
    {% else %}
    <p>Nejste přihlášen.</p>
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Odhlásit se</button>
    </form>

</div>
 
{% endblock %}